const constants = {
  POLICY_ID: 'b0fd70c54645a926e7a1e651869f93f1354245712c97128222805909',

  BLOCKFROST_API: 'https://cardano-mainnet.blockfrost.io/api/v0',
  BLOCKFROST_KEY: process.env.NEXT_PUBLIC_BLOCKFROST_KEY,

  FROG_FACTORY_WALLETS_STORAGE_KEY: 'FROG_FACTORY_WALLETS_STORAGE_KEY',
  SET_WALLETS: 'SET_WALLETS',
  ADD_WALLET: 'ADD_WALLET',
  DELETE_WALLET: 'DELETE_WALLET',

  TRAIT_CATEGORIES: [
    'BACKGROUND',
    'SKIN',
    'EYES',
    'CLOTHES',
    'HAT/HAIR',
    'MOUTH',
    'NOSE',
    'SPOTS',
  ],
}

module.exports = constants
